### PR TITLE
Dependabot update

### PR DESCRIPTION
**Pull request by ehanson8**
#### Helpful background context
Setting dependabot pip updates to weekly to reduce volume of PR emails tagged for DataEng review (186 in the last week for example) and updating dependencies.

#### How can a reviewer manually see the effects of these changes?
I triggered a run on dev1 this morning after pushing the updated image to ECR, the successful execution is under the name `alma-daily-ingest-2023-04-13t14-49-38`

#### Includes new or updated dependencies?
YES

#### Developer
- [x] All new ENV is documented in README
- [x] Stakeholder approval has been confirmed (or is not needed)

#### Code Reviewer
- [ ] The commit message is clear and follows our guidelines (not just this pull request message)
- [ ] There are appropriate tests covering any new functionality
- [ ] The documentation has been updated or is unnecessary
- [ ] The changes have been verified
- [ ] New dependencies are appropriate or there were no changes

### CODE REVIEW

**Comment by ehanson8** [comment]
I updated dependencies again, pushed the updated image to ECR and it kicked off the successful execution `alma-daily-ingest-2023-05-04t20-06-29`

**Comment by adamshire123** [comment]
> I updated dependencies again, pushed the updated image to ECR and it kicked off the successful execution `alma-daily-ingest-2023-05-04t20-06-29`

@ehanson8 what is `alma-daily-ingest-2023-05-04t20-06-29` - where can I see it?

**Comment by ehanson8** [comment]
Sorry, forgot to specify, in AWS Step Functions, `timdex-ingest-dev`

**Review by adamshire123 — APPROVED** [review]
Looks good to me

**Pull request merged**
